Try using SDL_CreateThread on Win32 to fix engine\portable\src\sys_system.c(264) : error C2440: 'function' : cannot convert from 'systhreadfunc_t' to 'LPTHREAD_START_ROUTINE' error exposed when using cmake and the visual studio generator. Hope I didn't screw it up any worse